window:
  name: "SURGE 2048"
  monitor_index: 1
  windowed: 1
  cursor: 1

resolution:
  width: 500
  height: 800

renderer:
  backend: 0 # 0 to OpenGL, 1 to Vulkan
  VSync: 1
  MSAA: 1
  fps_cap: 1 # Ignored on Windows
  fps_cap_value: 60

clear_color:
  r: 0.980
  g: 0.973
  b: 0.937
  a: 1.0

modules:
  first_module: "2048"
